// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skqpbsaosyyikqukmuro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrcXBic2Fvc3l5aWtxdWttdXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjgxNjEsImV4cCI6MjA3MjQ0NDE2MX0.svhh1qvtttHV6osFJSsMQ0gwY_4jJNpuoXF9Cx1x6cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});